 default: &default
   dispatchers:
     - polling_interval: 1
       batch_size: 500
   workers:
     - queues: "*"
       threads: 5
       processes: <%= Integer(ENV.fetch("WEB_CONCURRENCY") { Concurrent.physical_processor_count }) %>
       polling_interval: 0.1

 development:
  <<: *default

 test:
  <<: *default

 production:
  <<: *default
