source "https://rubygems.org"

ruby Pathname.new(__dir__).join(".ruby-version").read.strip

gem "bootsnap", require: false
gem "good_migrations"
gem "importmap-rails"
gem "jbuilder"
gem "puma", ">= 5.0"
gem "rack-canonical-host"
gem "rails", "~> 7.1.2"
gem "redis", ">= 4.0.1"
gem "sprockets-rails"
gem "sqlite3", "~> 1.4"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "launchy"
end

group :development do
  gem "annotate"
  gem "brakeman", require: false
  gem "bundler-audit", require: false
  gem "erb_lint", require: false
  gem "letter_opener"
  gem "rack-mini-profiler"
  gem "rubocop", require: false
  gem "rubocop-capybara", require: false
  gem "rubocop-factory_bot", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", ">= 2.22.0", require: false
  gem "tomo", "~> 1.18", require: false
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "capybara-lockstep"
  gem "selenium-webdriver"
  gem "shoulda-context"
  gem "shoulda-matchers"
  gem "vcr"
  gem "webmock"
end

group :production do
  gem "sidekiq", "~> 7.0"
end
