
node:
  description: "Set up Node and Yarn"

vite:
  description: "Replace the asset pipeline with Vite in app/frontend"
  requires: vite
  node: true

annotate:
  prompt: "Annotate Models"
  description: "Install annotate gem to auto-generate schema annotations"
  requires: active_record

capybara_lockstep:
  prompt: "capybara-lockstep"
  description: "Install capybara-lockstep gem for less-flaky browser testing"
  requires: system_testing

dotenv:
  prompt: "dotenv"
  description: "Install dotenv gem and add .env.sample"

factory_bot_rails:
  prompt: "Factory Bot"
  description: "Install and configure factory_bot_rails gem"
  requires: active_record

letter_opener:
  prompt: "letter_opener"
  description: "Install letter_opener gem to use with Action Mailer in dev"
  requires: action_mailer

open_browser_on_start:
  prompt: "Open browser on startup"
  description: "Configure puma to launch browser on startup in development"
  requires: frontend

pgcli_rails:
  prompt: "pgcli_rails"
  description: "Install pgcli_rails gem to allow easy use of pgcli"
  requires: postgresql

rack_canonical_host:
  prompt: "rack-canonical-host"
  description: "Install rack-canonical-host gem; use RAILS_HOSTNAME"

rack_mini_profiler:
  prompt: "rack-mini-profiler"
  description: "Install rack-mini-profiler gem in development"
  requires: frontend

shoulda:
  prompt: "shoulda"
  description: "Install shoulda-matchers gem for concise model testing"
  requires: test_framework

thor:
  prompt: "Thor"
  description: "Configure Thor for ease of writing Rails tasks"

tomo:
  prompt: "Tomo"
  description: "Install tomo gem for SSH-based deployment"

vcr:
  prompt: "VCR"
  description: "Install and configure vcr and webmock gems"
  requires: test_framework
