current: &current
  args: []
  label: "%%CURRENT_VERSION%%"
  asset_pipelines:
    sprockets: Sprockets (default)
    propshaft: Propshaft
  databases:
    sqlite3: SQLite3 (default)
    postgresql: PostgreSQL (recommended)
    mysql: MySQL
    trilogy: Trilogy
    oracle: Oracle
    sqlserver: SQLServer
    jdbcmysql: JDBCMySQL
    jdbcsqlite3: JDBCSQLite3
    jdbcpostgresql: JDBCPostgreSQL
    jdbc: JDBC
  default_features:
    brakeman: Brakeman
    ci: GitHub Actions CI
    rubocop: RuboCop
  optional_features:
    devcontainer: devcontainer files

edge:
  <<: *current
  args: ["--edge"]
  label: "edge (7-2-stable)"

main:
  args: ["--main"]
  label: "main (%%MAIN_VERSION%%)"
  asset_pipelines:
    propshaft: Propshaft (default)
    sprockets: Sprockets
  databases:
    sqlite3: SQLite3 (default)
    postgresql: PostgreSQL (recommended)
    mysql: MySQL
    trilogy: Trilogy
    oracle: Oracle
    sqlserver: SQLServer
    jdbcmysql: JDBCMySQL
    jdbcsqlite3: JDBCSQLite3
    jdbcpostgresql: JDBCPostgreSQL
    jdbc: JDBC
    mariadb-mysql: MariaDB-MySQL
    mariadb-trilogy: MariaDB-Trilogy
  default_features:
    brakeman: Brakeman
    ci: GitHub Actions CI
    kamal: Kamal
    rubocop: RuboCop
    solid: Solid Cache+Queue
    thruster: Thruster
  optional_features:
    devcontainer: devcontainer files
