#!/usr/bin/env ruby
# frozen_string_literal: true

require "nextgen"

# Work around an "unresolved or ambiguous specs" warning when CLI is run via `gem exec`
# https://github.com/rubygems/rubygems/issues/6914
at_exit do
  Gem.finish_resolve
rescue Exception # rubocop:disable Lint/RescueException
  # ignore
end

Nextgen::CLI.start
