version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
